import { eq } from 'drizzle-orm';
import { db } from '@/lib/db';
import { report } from '@/src/db/schema';
import type { Report, NewReport } from '../types';

/** Retrieve all reports */
export async function getAllReports(): Promise<Report[]> {
  return db.select().from(report);
}

/** Retrieve a single report by primary key */
export async function getReportById(id: number): Promise<Report | undefined> {
  const rows = await db.select().from(report).where(eq(report.reportId, id));
  return rows[0];
}

/** Retrieve all reports generated by a specific manager */
export async function getReportsByManagerId(managerId: number): Promise<Report[]> {
  return db.select().from(report).where(eq(report.managerId, managerId));
}

/** Retrieve all reports filtered by type */
export async function getReportsByType(type: string): Promise<Report[]> {
  return db.select().from(report).where(eq(report.reportType, type));
}

/** Insert a new report */
export async function createReport(data: NewReport): Promise<void> {
  await db.insert(report).values(data);
}

/** Update an existing report by ID */
export async function updateReport(id: number, data: Partial<NewReport>): Promise<void> {
  await db.update(report).set(data).where(eq(report.reportId, id));
}

/** Delete a report by ID */
export async function deleteReport(id: number): Promise<void> {
  await db.delete(report).where(eq(report.reportId, id));
}
